language: node_js

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(-\S*)?$/

cache:
  yarn: true
  directories:
    - node_modules

install: yarn --frozen-lockfile

before_deploy:
  - export NODE_DEBUG=gh-pages
  - find demo -type l | xargs sed -i '' || true # convert symlinks to regular files

deploy:
  - provider: script
    script: scripts/gh-pages.js
    skip_cleanup: true
    on:
      branch: master

  - provider: npm
    email: garden@zendesk.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      branch: master
      tags: true
