version: 2.1
orbs:
  node: circleci/node@2.1.0

references:
  workspace_root: &workspace_root ~/project

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  filters_tags: &filters_tags
    filters:
      tags:
        only: /.*/

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-key: yarn.lock
          pkg-manager: yarn
      - persist_to_workspace:
          root: *workspace_root
          paths: .

  test:
    executor: node/default
    steps:
      - *attach_workspace
      - run: yarn test

  deploy:
    executor: node/default
    environment:
      NODE_DEBUG: gh-pages
    steps:
      - *attach_workspace
      - run: find demo -type l | xargs sed -i '' || true # convert symlinks to regular files
      - run: scripts/deploy.js

  publish:
    executor: node/default
    steps:
      - *attach_workspace
      - run: npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run: yarn publish --ignore-scripts

workflows:
  main:
    jobs:
      - build:
          <<: *filters_tags
      - test:
          requires:
            - build
          <<: *filters_tags
      - deploy:
          requires:
            - test
          context: writer
      - publish:
          requires:
            - test
          context: maintainer
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+(-\S*)?$/
            branches:
              ignore: /.*/
